:repository-owner: traquito
:repository-name: WsprEncoded

= {repository-name} =

image:https://github.com/{repository-owner}/{repository-name}/actions/workflows/check-arduino.yml/badge.svg["Check Arduino status", link="https://github.com/{repository-owner}/{repository-name}/actions/workflows/check-arduino.yml"] +
image:https://github.com/{repository-owner}/{repository-name}/actions/workflows/compile-examples.yml/badge.svg["Compile Examples status", link="https://github.com/{repository-owner}/{repository-name}/actions/workflows/compile-examples.yml"]


This is the repo for standardizing and implementing the design of encoded WSPR messages as used by balloon trackers.


= Audience =

Developers of trackers.

Anyone else who wants to know.


= Goals =

Developers should be able to use this repo to:
- Understand the big idea
- Understand the specific technical details of how it works
- See implementation of library code
- See API usage and examples of code
- Acquire the library in a convenient way to use in their project
  - Requiring no modification whatsoever to work
  - Requiring no external or additional libraries to work


= Thoughts on technical details of how =

Need to decide between (say) wiki vs (say) markdown.

Markdown is simple to write, and get revision history.
- Generators can create nice documentation interfaces
  - [eg]()




= Other TODOs =

Write out CONTRIBUTING.md
